### ISSUE TITLE
Nuget packages fail to install in Visual Studio 2013/2015

### ISSUE THREAD

**Issue by kyberias** [joelself/FannCSharp#4]
I've tried this in both Visual Studio 2013 and Visual Studio 2015.
- Create a new Console application project (C#)
- Try to add FANNCSharp nuget package from nuget.org
- Both (x86,x64) result in error "failed to add reference to 'fanndouble'"
- Other nuget packages seem to install just fine

**Comment by discoHR** [comment]
Same here in Visual Studio 2015 Community Update 2.
I've downloaded and unzipped the required DLL files and they are in the reference path.
Getting an error and a warning:

```
E Failed to add reference to 'fanndouble'
W The referenced component 'FANNCSharp' could not be found
```

**Comment by joelself** [comment]
Yeah, it turns out that packaging managed and unmanaged dlls together is non-trivial. I've tried some solutions suggested online, but none of them seem to work. I think I'm just going to have to package the unmanaged binaries separately and then add them as a dependency.

**Comment by joelself** [comment]
I finally figured it out. It took a combination of steps that were in different answers to get it to work. For future reference this is how I got it to work. I mostly used [this answer on stackoverflow](http://stackoverflow.com/a/33041626):

> Add a build folder to the package and, if the package for example has the id MyPackage, add a MSBuild target file called MyPackage.targets to this folder. In the .nuspec file it looks like this:
> 
> ``` xml
> <files>
>     <file src="lib\*.*" target="lib" />
>     <file src="build\MyPackage.targets" target="build" />
> </files>
> ```
> 
> This will add an MSBuild element in the project file pointing to the .targets file.
> 
> The .targets file should look something like this:
> 
> ``` xml
> <?xml version="1.0" encoding="utf-8"?> 
> <Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003"> 
>   <Target Name="AfterBuild"> 
>     <ItemGroup> 
>       <MyPackageFiles Include="$(MSBuildProjectDirectory)\..\Packages\MyPackage\lib\*.*"/> 
>     </ItemGroup> 
>     <Copy SourceFiles="@(MyPackageFiles)" DestinationFolder="$(OutputPath)" > 
>     </Copy> 
>   </Target> 
> </Project>
> ```
> 
> Now, all files - including unmanaged files - will be copied to the project output folder (e.g. \bin\debug) after the build.

One problem I had was in the `MyPackageFiles` element's `Include` attribute I used the Id of my package "FANNCSharp-x64" when I needed the full name of the package: "FANNCSharp-x64.0.1.4".  Then the key piece to get it working comes [from the answer above](http://stackoverflow.com/a/23068433) the previous one:

> The nuspec reference now allows you to specify which DLLs in the lib directory get explicitly registered in the visual studio project now, you simply need to add into your nuspec file in the metadata area an explicit references list (if this does not exist the default behavior of nuget is to attempt to register everything under lib).

If you don't specifically reference which dlls to register, VS will try to register all of them by default (hence the `E Failed to add reference to 'fanndouble'`), so in the nuspec file I added:

``` xml
        <references>
            <reference file="FANNCSharp.dll" />
        </references>
```

under Packages -> Metadata. So now everything gets copied to the output directory, but only FANNCSharp.dll is registered.

I uploaded fixed packages, but they won't be searchable or installable for probably 30 - 60 minutes.

**Comment by joelself** [comment]
Had to release a new version 0.1.8 that doesn't coincide with any new release, but it works now.

**Comment by kyberias** [comment]
Great, thanks!
